[package]
name = "rust-relp-server"
version = "0.1.0"
authors = ["frankfarrell <ofearghp@gmail.com>"]

[dependencies]
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
regex = "0.2"
lazy_static = "1.0"